//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int oID { get; set; }

        [DisplayName("Customer Name")]
        public Nullable<int> cID { get; set; }

        [DisplayName("Product Name")]
        public Nullable<int> pID { get; set; }

        [DisplayName("Order Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> orderDate { get; set; }

        [DisplayName("Payment Status")]
        public Nullable<bool> paymentStatus { get; set; }

        [DisplayName("Quantity")]
        public Nullable<int> quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
